/* "@(#)Example.c Oct 11  5:21:55 2021" */
/* Generated by XDS Modula-2 to ANSI C v4.20 translator */

#define X2C_int32
#define X2C_index32
#ifndef X2C_H_
#include "X2C.h"
#endif
#define Example_C_
#ifndef UrlEncode_H_
#include "UrlEncode.h"
#endif
#ifndef InOut_H_
#include "InOut.h"
#endif

static urlString normalString;

static urlString encodedString;


X2C_STACK_LIMIT(8000000l)
extern int main(int argc, char **argv)
{
   urlString tmp;
   X2C_BEGIN(&argc,argv,1,20000000l,32000000l);
   InOut_BEGIN();
   strncpy(normalString,"https://www.google.com/search?q=$$rt(())kh7iwkf7 @el\
 jnk os",512u);
   memcpy(encodedString,UrlEncodeLight(tmp, normalString),512u);
   InOut_WriteString("Input: ", 8ul);
   InOut_WriteString(normalString, 512ul);
   InOut_WriteLn();
   InOut_WriteString("Output: ", 9ul);
   InOut_WriteString(encodedString, 512ul);
   InOut_WriteLn();
   strncpy(normalString,"VGVzdGluZyB*YXNlN+jQt/b2RlZCBzdHJpbmdzI?z?IHBhcmFtZX\
RlcnM=",512u);
   memcpy(encodedString,UrlEncodeFull(tmp, normalString),512u);
   InOut_WriteString("Input: ", 8ul);
   InOut_WriteString(normalString, 512ul);
   InOut_WriteLn();
   InOut_WriteString("Output: ", 9ul);
   InOut_WriteString(encodedString, 512ul);
   InOut_WriteLn();
   X2C_EXIT();
   return 0;
}

X2C_MAIN_DEFINITION
